### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Gideon877** [vtrev/BikeRide#1]
What's going on here?

@vtrev 

https://github.com/vtrev/BikeRide/blob/1cf6ab59982b0fc048b4c417fabd4630728ab769/src/bicycles/BicycleType.java#L7-L22

**Comment by vtrev** [comment]
@Gideon877  So that is the accelerationSpeed and the breakSpeed ints. The enum constructor assigns the values from the types,as it looks they have defined values. The getters are just sending those speeds out of the enum since they are private. I made this because I dropped the specifications class, the specs moved into the enum.
